version: 2.1

orbs:
  architect: giantswarm/architect@4.24.0

workflows:
  build:
    jobs:
      # Ensure that for every commit to master and for every
      # release tag, there is an app version in the catalog.
      - architect/push-to-app-catalog:
          context: architect
          name: push-to-app-catalog-master
          app_catalog: "giantswarm-playground-catalog"
          app_catalog_test: "giantswarm-playground-test-catalog"
          chart: "goldpinger"
          filters:
            tags:
              only: /^v.*/
