apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource.default.name" . }}
  annotations:
    giantswarm.io/monitoring: "true"
    prometheus.io/port: "8080"
  labels:
    app: {{ include "resource.default.name" . }}
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: {{ include "resource.default.name" . }}
