image:
  domain: docker.io
  name: "bloomberg/goldpinger"
  tag: "v3.7.0"

health_probes:
  dns_hosts: "giantswarm.io"
  dns_timeout: "500"
  http_target: "https://giantswarm.io"
  tcp_targets: ""
  tcp_timeout: "500"
